version: "3"

services:
  app:
    container_name: server-websocket-app-development
    build:
      context: .
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    entrypoint: dockerize -wait tcp://db:27017 -timeout 40s .docker/entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo-dev-server
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env
    links:
      - db

volumes:
  mongo-db:
